### ISSUE TITLE
Add in environment variables

### ISSUE THREAD

**Issue by perryhealy** [roirevolution/laptop#10]
- REQUIRE_FROM_DRIVE_SERVER_ADDRESS
 - REQUIRE_FROM_DRIVE_SERVER_TOKEN
 - ROI_REVOLUTION_NPM_TOKEN

A lot of these are secrets; we may just need to `echo` instructions

**Comment by tmr08c** [comment]
Since these are sort of secret, I'd think we'd want to avoid putting them in the repo. Could we set up a Google doc with instructions for what to do and how to set them up and link to that Doc in the README?

**Comment by amcheshire** [comment]
`ROI_REVOLUTION_NPM_TOKEN` is covered by [this](https://github.com/roirevolution/engineering/wiki/Set-up-npm-authentication), and require from drive is deprecated, so we can close this issue.
