### ISSUE TITLE
Determine if GUI apps can be installed as part of the laptop script

### ISSUE THREAD

**Issue by amcheshire** [roirevolution/laptop#8]
# The What
We have [a doc](https://docs.google.com/document/d/1H06w8yM4LiaaAcpu2_mzUtONvLLKE9OesC7xNqXavEs/edit?ts=5ccb1c05#bookmark=id.tez2krsdz2hk) that lists the desktop application we want to install for new hires.

Currently, we install these manually through a web browser. We should determine if we can instead make this part of the laptop setup script, and implement it if we can.

# The How
We think we may be able to  get Chrome installed with Brew Cask (https://github.com/Homebrew/homebrew-cask) (a way to use Homebrew to install GUI apps)

We should verify this and see if we can do the same for the other GUI/desktop apps that we need.

**Comment by tmr08c** [comment]
It looks like [cask is already set up](https://github.com/roirevolution/laptop/blob/master/mac#L112), so it may just work&trade;

**Comment by tmr08c** [comment]
It also looks like it may [uninstall cask](https://github.com/roirevolution/laptop/blob/master/mac#L101-L104), so we may want to test it. 

When setting up for interns, we should try adding a line like:

```bash
cask "google-chrome"
```

and see if it works.

**Comment by amcheshire** [comment]
We have IT install these apps ahead of time before they give the laptop to the new hire, so the need for this is low enough that we can close this.
